### ISSUE TITLE
chapter 4 - how do you run your app?

### ISSUE THREAD

**Issue by idawazoo** [PacktPublishing/Python-Microservices-Development#3]
i keep getting an error ModuleNotFoundError: No module named 'monolith.database'

could you include complete installation and running procedure?

**Comment by idawazoo** [comment]
this kinda worked for me? i am not sure since i am missing the strava client id and secret.

assuming flask/python3/pip3/virtualvenv installed

```
$ unzip monolith-master.zip
$ cd monolith-master
$ echo "Flask-SQLAlchemy" >> requirements.txt
$ virtualvenv venv --python=python3
$ . venv/bin/activate
$ pip install -r requirements.txt
$ export FLASK_APP=monolith/app.py
$ export STRAVA_CLIENT_ID=STRAVA_CLIENT_ID
$ export STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET
$ flask run
```

**Comment by tarekziade** [comment]
That looks right, do you still have some issues (sorry for the delay, this issue slip through my radars) - send me an e-mail if you still need help tarek@ziade.org

**Comment by githubce** [comment]
Hi @tarekziade 

I have added you to the repository.
You may directly commit code changes to the repository if needed.

Regards
