### ISSUE TITLE
Potential security issue 

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Python-Microservices-Development#5]
Hi, I would like to report a potential vulnerability in this project. May I know the security contact?

**Comment by ghost** [comment]
@ManikandanKurup-Packt Why was this closed? I understand the repo hosts sample code for a book but the code snippet in question has a critical security flaw and needs to be fixed. Please contact me at porcupineyhairs"you-know-the-character-here"wearehackerone.com. I will provide you with the details.

**Comment by ManikandanKurup-Packt** [comment]
Hi @porcupineyhairs 
Can you send us the details at manikandank@packt.com? The address that you gave seems incorrect.

**Comment by ghost** [comment]
@ManikandanKurup-Packt Any updates here? I sent you a mail with the details a few days back.

**Comment by ManikandanKurup-Packt** [comment]
@porcupineyhairs We have sent an email to the author about the issue and he is yet to respond. I'll get back to you once we have a reply from the author. 
Thanks!
